Enabler/1002/test collections on ansible core 2 16
ansible-collections/ibm_zos_core pull request #1053
Opened 2023-11-08 17:33 UTC by AndreMarcel99

##### SUMMARY
Add sanity ignores entries for running Ansible-core 2.16 on full regression.

##### ISSUE TYPE
- Docs Pull Request

##### ADDITIONAL INFORMATION
Update sanity ignores entries by adding licenses for Archive and Unarchive validate-modules:missing-gplv3-license.

2023-11-08 17:44 UTC, richp405 approved these changes

2023-11-08 17:45 UTC, fernandofloresg requested changes

2023-11-08 17:45 UTC, fernandofloresg commented on changelogs/fragments/1053-Enabler_1002_test_collections_on_ansible_core_2_16.yml
> +  - ignore-2.16 - add missing-gplv3-license ignore for archive and unarchive module.
name of the modules are zos_archive and zos_unarchive

2023-11-09 16:29 UTC, rexemin approved these changes
Looks good.

2023-11-09 16:53 UTC, fernandofloresg approved these changes

2023-11-09 16:56 UTC, merged