Enabler/990 991/sanity zos copy
ansible-collections/ibm_zos_core pull request #1307
Opened 2024-03-18 00:50 UTC by fernandofloresg

##### SUMMARY

##### ISSUE TYPE

- Bugfix Pull Request
- Docs Pull Request
- Feature Pull Request
- New Module Pull Request

##### COMPONENT NAME

##### ADDITIONAL INFORMATION

```paste below

```

2024-03-21 23:21 UTC, fernandofloresg commented
<img width="927" alt="Screenshot 2024-03-21 at 5 20 46 PM" src="https://github.com/ansible-collections/ibm_zos_core/assets/23223623/8cc78aa0-d8b2-4ca0-85b9-506030db317e">

2024-03-22 18:31 UTC, richp405 approved these changes
Changes look fine... am I correct that there is no changelog/fragment/(something).yaml file because this is internal, not customer-facing?

2024-03-29 15:05 UTC, rexemin requested changes
Looks good, I would just say to add a changelog fragment, even if it has a trivial tag

2024-03-29 17:05 UTC, rexemin approved these changes

2024-03-29 21:57 UTC, merged