Enabler/add ansible sanity action
ansible-collections/ibm_zos_core pull request #1313
Opened 2024-03-20 17:35 UTC by IsaacVRey

##### SUMMARY

#1312 

##### ISSUE TYPE

- Feature Pull Request

##### COMPONENT NAME

ac-ansible-test-sanity
##### ADDITIONAL INFORMATION

```paste below

```

2024-04-01 20:35 UTC, fernandofloresg approved these changes

2024-04-01 21:26 UTC, richp405 requested changes

2024-04-01 21:26 UTC, richp405 commented on .github/workflows/ac-ansible-test-sanity.yml
> +      - 'tests/sanity/ignore-2.9'
i would suggest either tests/sanity/ignore-* or adding 2.14 (I think the * would be easier to maintain)

2024-04-02 17:05 UTC, richp405 approved these changes

2024-04-02 19:49 UTC, AndreMarcel99 approved these changes

2024-04-02 23:36 UTC, merged