Documentation/module utils/import handler
ansible-collections/ibm_zos_core pull request #1332
Opened 2024-03-25 15:21 UTC by IsaacVRey

##### SUMMARY

#1311 

##### ISSUE TYPE
- Docs Pull Request

##### COMPONENT NAME

Update documentation on module utils to the google form

##### ADDITIONAL INFORMATION

```paste below

```

2024-04-18 21:20 UTC, fernandofloresg approved these changes

2024-04-18 21:34 UTC, rexemin requested changes
Looks good, just pointed out a little typo.

2024-04-18 21:34 UTC, rexemin commented on plugins/module_utils/import_handler.py
> +        """Error when it is unable to import a module due it being missing.
Just a little typo: instead of `...module due it being missing.`, it should be `...module due to it being missing.`

2024-04-19 16:09 UTC, richp405 approved these changes
I'll approve pending Ivan's note: one minor grammar fix.

2024-04-19 19:28 UTC, merged