[Enabler][test_zos_archive_func] Update test suites on functional/module-utils/test_zos_archive_func.py
ansible-collections/ibm_zos_core pull request #1448
Opened 2024-04-15 14:34 UTC by IsaacVRey

##### SUMMARY

Update test suites on functional/module-utils/test_zos_archive_func.py to be pylint correct.
This adresses part of #1441 

##### ISSUE TYPE

- Feature Pull Request

##### COMPONENT NAME

test_zos_archive_func.py

##### ADDITIONAL INFORMATION

```paste below

```

2024-06-04 19:23 UTC, richp405 approved these changes

2024-06-12 02:12 UTC, AndreMarcel99 commented
<img width="1268" alt="Captura de pantalla 2024-06-11 a la(s) 8 12 35 p m" src="https://github.com/ansible-collections/ibm_zos_core/assets/68956970/eec786cc-c24e-4b05-8a9e-214ab2374770">

2024-06-12 02:24 UTC, fernandofloresg commented
Is this consistency failing @AndreMarcel99 ? I have it running fine in #1511

2024-06-12 03:06 UTC, AndreMarcel99 commented
<img width="961" alt="Captura de pantalla 2024-06-11 a la(s) 9 06 09 p m" src="https://github.com/ansible-collections/ibm_zos_core/assets/68956970/17821b94-b174-404c-b3c9-99ec9ab771b0">

2025-04-01 13:24 UTC, richp405 approved these changes

2025-04-01 13:25 UTC, richp405 approved these changes

2025-04-01 15:06 UTC, fernandofloresg commented
@AndreMarcel99 As `dev` branch has been merged into this code and is over 6 months since testing. Could you run the test suite again ?

2025-04-01 16:05 UTC, AndreMarcel99 commented
@fernandofloresg the screenshot of run of the pipeline is from 21 March 
<img width="1725" alt="Captura de pantalla 2025-04-01 a la(s) 10 04 30 a m" src="https://github.com/user-attachments/assets/ac6871c8-f123-44bf-b19a-4d8415daddc2" />

2025-04-01 19:47 UTC, fernandofloresg requested changes
Left few questions about removing f-strings in favor of formatted strings, also requested a minor change

2025-04-01 19:47 UTC, fernandofloresg commented on tests/functional/modules/test_zos_archive_func.py
> +            "name":F"{pds_name}({member_base_name+str(i)})",
I know is possible to python to recognize f-strings with capital F but seems weird. 
```suggestion
            "name":f"{pds_name}({member_base_name+str(i)})",
```

2025-04-01 19:47 UTC, fernandofloresg commented on tests/functional/modules/test_zos_archive_func.py
> +                    name="{0}({1})".format(src_data_set, member),
Curious to see many other strings being converted to f-strings but this one is converted back to formatted strings?

2025-04-01 19:47 UTC, fernandofloresg commented on tests/functional/modules/test_zos_archive_func.py
> +                ds_to_write = "{0}({1})".format(src_data_set, member)
same question about formatted strings

2025-04-01 19:47 UTC, fernandofloresg commented on tests/functional/modules/test_zos_archive_func.py
> +                    name="{0}({1})".format(src_data_set, member),
Same question about f-strings being removed

2025-04-01 19:47 UTC, fernandofloresg commented on tests/functional/modules/test_zos_archive_func.py
> +                ds_to_write = "{0}({1})".format(src_data_set, member)
Same question about f-strings being removed

2025-04-02 15:43 UTC, AndreMarcel99 commented on tests/functional/modules/test_zos_archive_func.py
> +            "name":F"{pds_name}({member_base_name+str(i)})",
Typo I suppose

2025-04-02 15:47 UTC, AndreMarcel99 commented on tests/functional/modules/test_zos_archive_func.py
> +                    name="{0}({1})".format(src_data_set, member),
I'm curious about it too, because the better practice is to use f-strings

2025-04-04 17:01 UTC, fernandofloresg approved these changes
Thank you for addressing my comments!!

2025-04-04 18:02 UTC, merged