[Enabler][test_zos_job_submit_func] Update test suites on functional/modules/test_zos_job_submit_func.py to be pylint correct
ansible-collections/ibm_zos_core pull request #1464
Opened 2024-04-22 17:00 UTC by IsaacVRey

##### SUMMARY

Update test suites on functional/modules/test_zos_job_submit_func.py to be pylint correct.
This adresses part of #1441 

##### ISSUE TYPE

- Feature Pull Request

##### COMPONENT NAME

test_zos_job_submit_func.py

##### ADDITIONAL INFORMATION

```paste below

```

2024-06-04 18:26 UTC, richp405 approved these changes

2024-06-06 18:09 UTC, AndreMarcel99 commented
<img width="1423" alt="Captura de pantalla 2024-06-06 a la(s) 11 56 43 a m" src="https://github.com/ansible-c
<img width="1442" alt="Captura de pantalla 2024-06-06 a la(s) 12 09 52 p m" src="https://github.com/ansible-collections/ibm_zos_core/assets/68956970/4c41c9dc-c66c-43af-9732-2a65e8bf8305">
ollections/ibm_zos_core/assets/68956970/a0bf9718-0c9b-4914-8f4e-057c525dc1da">

2024-06-07 19:46 UTC, rexemin approved these changes

2024-06-12 02:27 UTC, fernandofloresg commented
Will manually test this since is failing for marcel

2024-06-12 02:27 UTC, fernandofloresg requested changes
Need to test failing test case

2024-06-13 16:35 UTC, fernandofloresg approved these changes

2024-06-13 16:35 UTC, merged