[Enabler][test_zos_tso_command_func] Update test suites on functional/modules/test_zos_tso_command_func.py to be pylint correct
ansible-collections/ibm_zos_core pull request #1480
Opened 2024-04-24 19:29 UTC by IsaacVRey

##### SUMMARY

Update test suites on functional/modules/test_zos_tso_command_func.py to be pylint correct.
This adresses part of #1441 

##### ISSUE TYPE

- Feature Pull Request

##### COMPONENT NAME

test_zos_tso_command_func.py

##### ADDITIONAL INFORMATION

```paste below

```

2024-06-03 21:19 UTC, richp405 approved these changes

2024-06-03 21:42 UTC, rexemin approved these changes

2024-06-04 20:21 UTC, fernandofloresg requested changes
a lot of changes have happened in the code since this PR was opened, will run the test suite before approving

2024-06-04 23:48 UTC, AndreMarcel99 commented
<img width="1191" alt="Captura de pantalla 2024-06-04 a la(s) 5 47 48 p m" src="https://github.com/ansible-collections/ibm_zos_core/assets/68956970/a73a13f2-e261-4ab9-ab17-70aa69bf498c">

2024-06-05 20:33 UTC, fernandofloresg approved these changes

2024-06-05 20:33 UTC, merged