[Enabler][test_zos_unarchive_func] Update test suites on functional/modules/test_zos_unarchive_func.py to be pylint correct
ansible-collections/ibm_zos_core pull request #1483
Opened 2024-04-25 17:50 UTC by IsaacVRey

##### SUMMARY

Update test suites on functional/modules/test_zos_unarchive_func.py to be pylint correct.
This adresses part of #1441 

##### ISSUE TYPE

- Feature Pull Request

##### COMPONENT NAME

test_zos_unarchive_func.py

##### ADDITIONAL INFORMATION

```paste below

```

2024-06-13 18:56 UTC, AndreMarcel99 commented
<img width="1322" alt="Captura de pantalla 2024-06-13 a la(s) 12 55 57 p m" src="https://github.com/ansible-collections/ibm_zos_core/assets/68956970/89a5deff-5ec4-4514-b7c6-b49ffe037884">

2024-06-17 20:07 UTC, richp405 approved these changes

2025-04-01 20:41 UTC, AndreMarcel99 commented
<img width="1382" alt="Captura de pantalla 2025-04-01 a la(s) 2 41 31 p m" src="https://github.com/user-attachments/assets/a3e0f003-f9c2-40da-91a6-14691ff3d7ca" />
<img width="577" alt="Captura de pantalla 2025-04-01 a la(s) 2 41 42 p m" src="https://github.com/user-attachments/assets/4c07f886-b3dd-4f60-ad63-aca89e23aac1" />

2025-04-01 22:23 UTC, rexemin approved these changes

2025-04-01 23:08 UTC, fernandofloresg requested changes
Request minor change and a question

2025-04-01 23:08 UTC, fernandofloresg commented on tests/functional/modules/test_zos_unarchive_func.py
> +        hosts.all.shell(cmd=f"drm {dataset.replace}*")
Looks like this line would not replace the data set, tested this and while it won't break it would replace the data set name with a function definition.

Example vs replacing it with arguments
```python
>>> dataset = "asad"
>>> a = f"{dataset.replace}*"
>>> print(a)
<built-in method replace of str object at 0x103523600>*
>>> a = f"{dataset.replace("s", "")}*"
>>> print(a)
aad*
```

2025-04-01 23:08 UTC, fernandofloresg commented on tests/functional/modules/test_zos_unarchive_func.py
> +            cmd_result = hosts.all.shell(cmd=f"""dls "{hlqua}.*" """)
Why is this variable named `hlqua` and not simply `hlq`?

2025-04-01 23:08 UTC, fernandofloresg commented on tests/functional/modules/test_zos_unarchive_func.py
> +            cmd_result = hosts.all.shell(cmd=f"""dls "{hlqua}.*" """)
not a dealbreaker but just a question

2025-04-02 13:14 UTC, richp405 approved these changes
Looks okay from here..

2025-04-02 15:42 UTC, AndreMarcel99 commented on tests/functional/modules/test_zos_unarchive_func.py
> +        hosts.all.shell(cmd=f"drm {dataset.replace}*")
Thank's that was a bad copy

2025-04-02 21:27 UTC, AndreMarcel99 commented
<img width="1364" alt="Captura de pantalla 2025-04-02 a la(s) 3 27 36 p m" src="https://github.com/user-attachments/assets/6e36821b-b216-47a7-b6cf-84450465119f" />
<img width="727" alt="Captura de pantalla 2025-04-02 a la(s) 3 27 44 p m" src="https://github.com/user-attachments/assets/55415621-29e0-4162-87f6-a790e2380b9b" />

2025-04-04 16:46 UTC, fernandofloresg commented on tests/functional/modules/test_zos_unarchive_func.py
> +            cmd_result = hosts.all.shell(cmd=f"""dls "{hlqua}.*" """)
cool not a dealbreaker

2025-04-04 16:46 UTC, fernandofloresg approved these changes
LGTM ! Thanks for the changes

2025-04-04 16:48 UTC, merged