Enabler/1374/zos find gdg gds special chars
ansible-collections/ibm_zos_core pull request #1518
Opened 2024-05-23 14:17 UTC by richp405

##### SUMMARY
Add support and test for GDG data set convention, and validate special-character use in ds names

Addresses 1374

##### ISSUE TYPE
- Feature Pull Request

##### COMPONENT NAME
zos_find

##### ADDITIONAL INFORMATION

2024-05-23 14:17 UTC, richp405 commented
![image](https://github.com/ansible-collections/ibm_zos_core/assets/39140439/2e29bff9-56a1-4eb3-87fd-995184845f9c)

2024-05-23 14:25 UTC, richp405 commented
I had to re-push, because dev changed while I was testing.

2024-05-23 19:59 UTC, fernandofloresg requested changes

2024-05-23 21:08 UTC, fernandofloresg commented on tests/functional/modules/test_zos_find_func.py
Hey Rich, I don't know if this was added into the development task but I think we also should be able to filter the GDGs by its attributes, I mean, return GDGs with purge = True or return where extended = True. Is that something that can be added in this same task ?

2024-05-23 21:13 UTC, richp405 commented on tests/functional/modules/test_zos_find_func.py
I'll check on Friday for this... not sure, offhand, but we can touch up the interface.

2024-05-23 21:15 UTC, richp405 commented on tests/functional/modules/test_zos_find_func.py
> +GDG_NAMES = [
I'll read through that... the reasons it was hardcoded before is that the testing was checking for the files with asterisks (like test.find.pds.*).. I think I can work up a compromise (like test.find.pds.randomname?)

2024-05-24 20:20 UTC, richp405 commented on tests/functional/modules/test_zos_find_func.py
It's a good thought, but I think we'll do it in a separate ticket, because changing the interface needs to be separate from adding options.  We can still fit this into 1.11-b1

2024-05-24 20:20 UTC, richp405 commented on tests/functional/modules/test_zos_find_func.py
> +GDG_NAMES = [
I'm working through the change to run the tests against variable names.  good idea.  It will be ready Tuesday.

2024-05-27 15:59 UTC, fernandofloresg requested changes
I code wise test is good. The only thing I would ask to add that is in the issue description is to modify the zos_apf docs to include the fact that GDGs are now supported.

2024-05-27 15:59 UTC, fernandofloresg commented on tests/functional/modules/test_zos_find_func.py
Sure, I noticed is not mentioned in the base issue, my bad.

2024-05-29 18:13 UTC, richp405 commented on tests/functional/modules/test_zos_find_func.py
Added #1524 as new enhancement to split up the work.

2024-05-29 18:20 UTC, richp405 commented on tests/functional/modules/test_zos_find_func.py
> +GDG_NAMES = [
Make that Friday of this week.  I'll re-issue invites then.

2024-05-29 19:27 UTC, fernandofloresg commented on tests/functional/modules/test_zos_find_func.py
Great thanks Rich!

2024-05-29 19:27 UTC, fernandofloresg commented on tests/functional/modules/test_zos_find_func.py
> +GDG_NAMES = [
Sure, I don't expect you to change all tests just this one to not introduce new hardcoded content.

2024-07-12 19:18 UTC, fernandofloresg approved these changes
I did some changes myself, hence moving from changes requested to approved. Will merge once we have 3 approvals

2024-07-15 04:32 UTC, fernandofloresg commented
<img width="1075" alt="Screenshot 2024-07-14 at 10 32 15 PM" src="https://github.com/user-attachments/assets/c22846c1-77ed-454f-b609-7b1c6eb2af49">

2024-07-15 22:16 UTC, rexemin approved these changes

2024-07-17 16:08 UTC, merged