Enabler/1377/mvs raw support gdg gds special characcter
ansible-collections/ibm_zos_core pull request #1525
Opened 2024-05-29 20:47 UTC by AndreMarcel99

##### SUMMARY

Fixes #1377 

##### ISSUE TYPE

- Enabler Pull Request

##### COMPONENT NAME
Add function resolve_data_set_names for dd_data_set

##### ADDITIONAL INFORMATION
When get key values of the dd's at the moment to check dd_dataset check for the data_set_name (required parameter) by first check if is a relative positive if the disposition is new will work properly other case will check if the data set exist and disposition is new it will fail other case return the absolute name.

2024-05-30 19:46 UTC, AndreMarcel99 commented
Changes on` plugins/module_utils/data_set.py` are from block and lineinfile work, that's why I didn't test

2024-05-30 20:17 UTC, richp405 approved these changes

2024-05-31 17:20 UTC, fernandofloresg requested changes
Just left a few suggestions

2024-05-31 17:20 UTC, fernandofloresg commented on plugins/modules/zos_mvs_raw.py
> +                raise ("To generate a new gds as {0} required disposition new".format(dataset))
```suggestion
                raise ("To generate a new GDS as {0} disposition 'new' is required.".format(dataset))
```

2024-05-31 17:20 UTC, fernandofloresg commented on plugins/modules/zos_mvs_raw.py
> +                    raise ("Gds {0} already create, incorrect parameters {1} and {2}".format(src, "disposition", "data_set_name"))
```suggestion
                    raise ("GDS {0} already created, use a positive generation when disposition  '{1}' is used.".format(src, "disposition", "data_set_name"))
```

2024-05-31 20:44 UTC, fernandofloresg commented on plugins/modules/zos_mvs_raw.py
> +                    raise ("Gds {0} already create, incorrect parameters for disposition and data_set_name".format(src))
```suggestion
                    raise ("GDS {0} already created, incorrect parameters for disposition and data_set_name".format(src))
```

2024-05-31 22:38 UTC, fernandofloresg approved these changes

2024-06-03 22:35 UTC, ketankelkar approved these changes

2024-06-04 20:17 UTC, merged