raise exception when mvscmd fails; add supporting unit tests
ansible-collections/ibm_zos_core pull request #1535
Opened 2024-06-06 00:27 UTC by ketankelkar

##### SUMMARY

Fixes:
- #838 

`DataSet.data_set_cataloged` function previously only returned `True` or `False`, but failed to account for exceptions which occurred during the LISTCAT.

The fix now raises an `MVSCmdExecError` if the return code from LISTCAT is too high.

This PR also introduces a new unit test file for module_utils/data_set.py. The unit tests do NOT check any functionality as they never connect to an actual z/OS system. A DummyModule steps in whenever the AnsibleModuleHelper object is invoked, in this case, namely when `run_command` is invoked to execute an `mvscmd` to invoke `IDCAMS`'s `LISTCAT ENTRIES` command. PS, i tried to use the word `invoke` as frequently as possible in that last sentence. The DummyModule takes as parameters `rc, stdout, and stderr` and spits them right back as the return structure for the defined `run_command`. The test contains string output from successful and failed invocations of `mvscmd` and paired with the appropriate `rc`, these unit tests mock the behavior of LISTCAT and allow the code paths in the `data_set_cataloged` function to be exercised. 

##### ISSUE TYPE

- Enhancement Pull Request

##### COMPONENT NAME

ibm.ibm_zos_core.plugins.module_utils.data_set.py::DataSet.data_set_cataloged().

2024-06-06 22:33 UTC, fernandofloresg approved these changes
lgtm!

2024-06-12 02:24 UTC, fernandofloresg approved these changes

2024-06-28 16:48 UTC, fernandofloresg requested changes
Excellent work, just one comment

2024-06-28 16:48 UTC, fernandofloresg commented on changelogs/fragments/838-raise-error-in-module-util-data_set-function-data_set_cataloged.yml
just the name of this file should be 1535 instead of 838

2024-07-01 17:58 UTC, fernandofloresg approved these changes
Great work!

2024-07-03 16:04 UTC, richp405 approved these changes

2024-07-04 03:37 UTC, ketankelkar commented
Since data set has a lot of test cases, i ran them separately. Since I ran them separately, the screenshots with the full green pipeline run are not possible since they went off the buffer. Instead, i've included the job numbers from my personal internal pipeline along with screenshots of the completion status:


- tests/functional/modules/test_zos_job_query_func.py (build 252)
  - <img width="511" alt="image" src="https://github.com/ansible-collections/ibm_zos_core/assets/10567394/220fcd85-cba9-4815-a017-fdabe8a5cfa5">
- tests/functional/modules/test_zos_encode_func.py (build 270)
  - <img width="497" alt="image" src="https://github.com/ansible-collections/ibm_zos_core/assets/10567394/64ccb8a0-7ba9-478f-baa9-643980acfc06">

- tests/functional/modules/test_zos_mount_func.py
  - This test suite was successful locally.

- tests/functional/modules/test_zos_copy_func.py (build 326)
  - <img width="490" alt="image" src="https://github.com/ansible-collections/ibm_zos_core/assets/10567394/f2097181-28fc-494b-b04a-c2e8b02a0a02">
- tests/functional/modules/test_zos_job_submit_func.py (build 271)
  - <img width="490" alt="image" src="https://github.com/ansible-collections/ibm_zos_core/assets/10567394/dc907de7-28ec-4368-a10e-9c16cff0a4c0">
- tests/functional/modules/test_zos_script_func.py (build 327)
  - <img width="490" alt="image" src="https://github.com/ansible-collections/ibm_zos_core/assets/10567394/92ad006d-1568-4102-8590-edbd0aec1bbb">
- tests/unit/test_zos_mvs_raw_unit.py (build 261)
  - <img width="490" alt="image" src="https://github.com/ansible-collections/ibm_zos_core/assets/10567394/d3142b97-d9c6-4b14-8f2b-4f50166570ea">
- tests/functional/modules/test_zos_volume_init_func.py (build 260)
  - <img width="490" alt="image" src="https://github.com/ansible-collections/ibm_zos_core/assets/10567394/6aca9036-38e0-49a5-80ab-c982eaddfb9a">
- tests/unit/test_zos_backup_restore_unit.py (build 261)
  - <img width="490" alt="image" src="https://github.com/ansible-collections/ibm_zos_core/assets/10567394/d3142b97-d9c6-4b14-8f2b-4f50166570ea">

- tests/functional/modules/test_zos_archive_func.py (build )
  - PENDING - see build 304 for passing func tests

- tests/functional/modules/test_zos_blockinfile_func.py (build 328)
  - <img width="490" alt="image" src="https://github.com/ansible-collections/ibm_zos_core/assets/10567394/260a3259-ee6d-41e4-b70f-be7afaf2913c">

- tests/functional/modules/test_zos_backup_restore.py (build)
  - PENDING - see build 299 for passing func tests
- tests/functional/modules/test_zos_unarchive_func.py (build 335)
  - <img width="490" alt="image" src="https://github.com/ansible-collections/ibm_zos_core/assets/10567394/b7f65b03-3544-4995-ab61-87c318c86167">

- tests/functional/modules/test_zos_data_set_func.py (build 333)
  - <img width="490" alt="image" src="https://github.com/ansible-collections/ibm_zos_core/assets/10567394/114f85a0-c166-4846-8fc2-2d50fcb6c731">

- tests/functional/modules/test_zos_find_func.py (build 332)
  - <img width="490" alt="image" src="https://github.com/ansible-collections/ibm_zos_core/assets/10567394/74aa151b-0a23-4018-912d-f2590f3c6454">

- tests/unit/test_module_utils_data_set_unit.py (build 261)
  - <img width="490" alt="image" src="https://github.com/ansible-collections/ibm_zos_core/assets/10567394/d3142b97-d9c6-4b14-8f2b-4f50166570ea">
- tests/functional/modules/test_zos_fetch_func.py (build 330)
  - <img width="490" alt="image" src="https://github.com/ansible-collections/ibm_zos_core/assets/10567394/607118b4-3e6f-488c-8047-e2571f2a77fc">

- tests/functional/modules/test_zos_apf_func.py (build 281)
  - <img width="490" alt="image" src="https://github.com/ansible-collections/ibm_zos_core/assets/10567394/35348503-7d38-43ff-813a-f80550aa9e98">
- tests/functional/modules/test_zos_lineinfile_func.py (build 280)
  - <img width="490" alt="image" src="https://github.com/ansible-collections/ibm_zos_core/assets/10567394/ee1b70a7-5ce4-4f97-9763-a858b8f82e07">
- tests/functional/modules/test_zos_mvs_raw_func.py (build 279)
  - <img width="490" alt="image" src="https://github.com/ansible-collections/ibm_zos_core/assets/10567394/2cb9482a-bdd6-4fe6-8c09-813a144315a2">
- tests/functional/modules/test_zos_job_output_func.py (build 278)
  - <img width="490" alt="image" src="https://github.com/ansible-collections/ibm_zos_core/assets/10567394/23604277-62db-469a-8c09-5f07e4a50ba9">

2024-07-09 04:36 UTC, merged