[Bugfix][822]lower_case_idcams_utility
ansible-collections/ibm_zos_core pull request #1550
Opened 2024-06-25 20:06 UTC by AndreMarcel99

##### SUMMARY

##### ISSUE TYPE

- Bugfix Pull Request
- Docs Pull Request
- Feature Pull Request
- New Module Pull Request

##### COMPONENT NAME

##### ADDITIONAL INFORMATION

```paste below

```

2024-06-28 16:43 UTC, fernandofloresg requested changes
Would like to see a test case added, else how would we know it is working now?

2024-06-28 19:01 UTC, richp405 approved these changes

2024-06-28 20:22 UTC, rexemin commented on changelogs/fragments/1550-lower_case_idcams_utility.yml
> +  - zos_operator - Pass to capital letters the command to idcams utility.
Would rephrase this to `Pass capital letters to the command...`

2024-07-15 16:06 UTC, AndreMarcel99 commented
@fernandofloresg I just modify zos find test case to validate by calling a case is calling the function

2024-07-15 16:23 UTC, fernandofloresg approved these changes

2024-07-15 16:24 UTC, merged