[Bugfix] [zos_job_output] [zos_job_query] Fix username validator in job util
ansible-collections/ibm_zos_core pull request #1661
Opened 2024-08-19 21:58 UTC by rexemin

##### SUMMARY
Fixes #1486.

##### ISSUE TYPE
- Bugfix Pull Request

##### COMPONENT NAME
- module_utils/job.py

##### ADDITIONAL INFORMATION
Added a new validator function inside the job util. Can change the function from the util to the BetterArgParser file if needed. Didn't change the qualifier validator previously used since job IDs do not use @, #, or $.

2024-08-20 19:31 UTC, rexemin commented
![Screenshot 2024-08-20 at 13 30 29](https://github.com/user-attachments/assets/cfbba9c1-1fdd-4f15-bc8d-9c876d83264e)
![Screenshot 2024-08-20 at 13 30 40](https://github.com/user-attachments/assets/d120580c-7aa4-44e3-9d86-547d3d785729)

2024-08-20 20:30 UTC, richp405 approved these changes

2024-08-21 19:18 UTC, fernandofloresg requested changes
Just requested a couple of changes. It seems correct to use a new type to validate username instead of modifying the job_id type.

2024-08-21 19:18 UTC, fernandofloresg commented on changelogs/fragments/1661-job-owner-valid-characters.yml
> +  - zos_job_output - RACF user names containing a ``@`` raised an invalid
I think you can add another sample of failing character or just say it didn't work with other special characters.

`RACF user names containing a ``@`` or other special characters raised an invalid argument error.`

2024-08-21 19:18 UTC, fernandofloresg commented on plugins/module_utils/job.py
> +def _username_pattern(contents, resolve_dependencies):
other type validations are in `plugins/module_utils/better_arg_parser.py` I think this should be included there too.

2024-08-22 17:12 UTC, fernandofloresg approved these changes
lgtm

2024-08-22 20:31 UTC, AndreMarcel99 approved these changes

2024-08-26 19:16 UTC, merged