[Enabler][1596]portability_zos_blockinfile
ansible-collections/ibm_zos_core pull request #1676
Opened 2024-08-28 20:40 UTC by AndreMarcel99

##### SUMMARY
Fix hardcoded datasets files names and hlq

Fixes #1596 

##### ISSUE TYPE

- Enabler Pull Request

##### ADDITIONAL INFORMATION
<img width="1356" alt="Captura de pantalla 2024-08-28 a la(s) 2 40 12 p m" src="https://github.com/user-attachments/assets/ab6a3599-8f98-4a6a-90cc-5f06e1b7367d">
<img width="511" alt="Captura de pantalla 2024-08-28 a la(s) 2 40 24 p m" src="https://github.com/user-attachments/assets/b30b5c3e-5699-4938-b844-a7f6fdc27f6a">

2024-08-28 21:04 UTC, richp405 approved these changes

2024-08-29 16:41 UTC, fernandofloresg requested changes
Just requested a couple of changes. Thank you for fixing the merge issues.

2024-08-29 16:41 UTC, fernandofloresg commented on tests/functional/modules/test_zos_blockinfile_func.py
> -    full_path = TEST_FOLDER_BLOCKINFILE + inspect.stack()[0][3]
So happy that you've removed inspect.stack. from naming generation, can you remove the import in line 17 as well :)

2024-08-29 16:41 UTC, fernandofloresg commented on tests/functional/modules/test_zos_blockinfile_func.py
Can you also remove the hard coded temporary folders? You can find them searching for "/tmp/" found some in several lines : 
44, 1038, 1064, 1090, ... 1414, 1416, 1417. 
Of these, 1038, 1064, 1090 seem ok to keep the same way, since those create temp names like this :
```
temp_file = "/tmp/" + ds_name
```
But can be changed to :

```
temp_file = TMP_DIRECTORY + ds_name
```
or 
```
temp_file = get_random_file_name(dir=TMP_DIRECTORY)
```
So, I'm not requesting those to be changed, but will be nice to have them create random file names the same way.

Found around 30 occurrences, not all of them must be changed but please update the ones that are not needed.

2024-08-29 17:18 UTC, fernandofloresg requested changes
thanks for the update but line 44, and the different lock related mechanisms need to be updated, some are still using 
/tmp/disp_shr

1282 is using the following 
hosts.all.shell(cmd="rm -rf " + "/tmp/zos_lineinfile/")

I'm just searching for "/tmp/" and seeing the occurrences, do recommend you do the same and remove them where applicable

2024-08-29 17:18 UTC, fernandofloresg commented on tests/functional/modules/test_zos_blockinfile_func.py
> -    params = {
Wasn't this a change Isaac did to make the tests more _pythonic_? why is this changed?

2024-09-03 18:13 UTC, AndreMarcel99 commented
<img width="1540" alt="Captura de pantalla 2024-09-03 a la(s) 12 13 11 p m" src="https://github.com/user-attachments/assets/a72cd1e8-7afb-44d6-be77-f3e5554b85f1">

2024-09-04 16:13 UTC, rexemin approved these changes

2024-09-04 17:16 UTC, fernandofloresg approved these changes
LGTM ! Thank you for performing the changes requested 😄

2024-09-04 17:17 UTC, merged