Avoid parsing
ansible-collections/ibm_zos_core pull request #1751
Opened 2024-10-16 17:15 UTC by AndreMarcel99

##### SUMMARY

##### ISSUE TYPE

- Bugfix Pull Request
- Docs Pull Request
- Feature Pull Request
- New Module Pull Request

##### COMPONENT NAME

##### ADDITIONAL INFORMATION

```paste below

```

2024-10-18 13:25 UTC, richp405 approved these changes

2024-10-18 16:26 UTC, fernandofloresg requested changes

2024-10-18 16:26 UTC, fernandofloresg commented on changelogs/fragments/1751-Avoid_parsing_on_job_utils.yml
> +minor_changes:
Should be trivial since is not a client facing change

2024-10-18 16:26 UTC, fernandofloresg commented on changelogs/fragments/1751-Avoid_parsing_on_job_utils.yml
> +  - module_utils/job.py - Avoid parsing of job output and use new job type on ZOAU pytho API.
I don't think it is job type but rather job class. Also a typo 

```suggestion
  - module_utils/job.py - Avoid parsing of job output and use job class from ZOAU python API.
```

2024-10-18 22:56 UTC, ketankelkar submitted a review, later dismissed
This LGTM pending Fernando's suggested changes

2024-10-22 20:05 UTC, fernandofloresg approved these changes

2024-10-22 20:05 UTC, merged