Enabler/1652/migrate shell call cp to python module
ansible-collections/ibm_zos_core pull request #1816
Opened 2024-11-28 02:13 UTC by AndreMarcel99

##### SUMMARY
Migrate call from cp to python API dataset.copy 
Fixes #1652 
##### ISSUE TYPE

- Enabler Pull Request

##### ADDITIONAL INFORMATION

![Captura de pantalla 2024-11-27 a la(s) 8 12 52 p m](https://github.com/user-attachments/assets/86f3b2c5-e20c-461b-b733-5d2283d51758)
![Captura de pantalla 2024-11-27 a la(s) 8 13 07 p m](https://github.com/user-attachments/assets/e54484bc-0697-4ec9-808d-5724aa538d1b)

2024-12-02 15:39 UTC, fernandofloresg requested changes

2024-12-02 16:14 UTC, richp405 requested changes

2024-12-02 16:14 UTC, richp405 commented on plugins/modules/zos_fetch.py
>          if rc != 0:
Also, I don't see wher 'out' is being assigned with the new call, so I think it needs loaded or the splitline will fail.

2024-12-02 21:14 UTC, AndreMarcel99 commented
![Captura de pantalla 2024-12-02 a la(s) 3 14 10 p m](https://github.com/user-attachments/assets/4b9efd2a-dec3-4e5f-8004-21b26ef14e44)
![Captura de pantalla 2024-12-02 a la(s) 3 14 19 p m](https://github.com/user-attachments/assets/3254ed22-2ff3-4442-9d0a-76f5fe5136e0)

2024-12-03 16:54 UTC, fernandofloresg approved these changes

2024-12-03 17:40 UTC, richp405 approved these changes
I see the assignment now.  thanks for that!

2024-12-04 17:20 UTC, merged