[enabler][zos_copy]Add_error_message
ansible-collections/ibm_zos_core pull request #1821
Opened 2024-11-29 18:37 UTC by AndreMarcel99

##### SUMMARY
Add validation for source members that does not exist 
Fixes #1010 

##### ISSUE TYPE

- Enabler Pull Request

##### ADDITIONAL INFORMATION
Add extra validation for any source member that does not exist

```paste below
TASK [Execute a copy expecting to fail] *************************************************************************************************************************************************************
fatal: [zvm]: FAILED! => {"changed": false, "msg": "Unable to execute copy. Source member does not exist MEMBER.", "rc": null, "stderr": null, "stderr_lines": null, "stdout": null, "stdout_lines": null}
```

2024-12-04 17:31 UTC, fernandofloresg requested changes

2024-12-04 17:31 UTC, fernandofloresg commented on changelogs/fragments/1821-Add_error_message.yml
I think this can be said in a simpler way, like,


Adds error message when a PDS/E source member does not exist or is not cataloged.

2024-12-05 15:42 UTC, richp405 approved these changes

2024-12-09 18:52 UTC, fernandofloresg approved these changes

2024-12-10 16:44 UTC, merged