Release v1.4.0 beta.2 rc
ansible-collections/ibm_zos_core pull request #529
Opened 2022-10-13 20:44 UTC by ddimatos

Version 1.4.0-beta.2
===============

* Bug fixes and enhancements

  * Modules

    * ``zos_copy``

      * introduced an updated creation policy referred to as precedence rules
        that if `dest_data_set` is set, it will take precedence. If
        `dest` is an empty data set, the empty data set will be written with the
        expectation its attributes satisfy the copy. If no precedent rule
        has been exercised, `dest` will be created with the same attributes of
        `src`.
      * introduced new computation capabilities that if `dest` is a nonexistent
        data set, the attributes assigned will depend on the type of `src`. If
        `src` is a USS file, `dest` will have a Fixed Block (FB) record format
        and the remaining attributes will be computed. If `src` is binary,
        `dest` will have a Fixed Block (FB) record format with a record length
        of 80, block size of 32760, and the remaining attributes will be
        computed.
      * enhanced the force option when `force=true` and the remote file or
        data set `dest`` is NOT empty, the `dest` will be deleted and recreated
        with the `src` data set attributes, otherwise it will be recreated with
        the `dest` data set attributes.
      * was enhanced for when `src` is a directory and ends with "/",
        the contents of it will be copied into the root of `dest`. It it doesn't
        end with "/", the directory itself will be copied.
      * option `dest_dataset` has been deprecated and removed in favor
         of the new option `dest_data_set`.
      * fixes a bug that when a directory is copied from the controller to the
        managed node and a mode is set, the mode is applied to the directory
        on the managed node. If the directory being copied contains files and
        mode is set, mode will only be applied to the files being copied not the
        pre-existing files.
      * fixes a bug that did not create a data set on the specified volume.
      * fixes a bug where a number of attributes were not an option when using
        `dest_data_set`.
      * fixes a bug where options were not defined in the module
        argument spec that will result in error when running `ansible-core`
        v2.11 and using options `force` or `mode`.

    * ``zos_operator``

      * enhanced to allow for MVS operator `SET` command, `SET` is
        equivalent to the abbreviated `T` command.

    * ``zos_mount``

      * fixed option `tag_ccsid` to correctly allow for type int.

    * ``module_utils``

      * jobs.py - fixes a utility used by module `zos_job_output` that would
        truncate the DD content.

  * Documentation

    * Review `version 1.4.0-beta.1` release notes for additional content.

* Deprecated or removed

  * ``zos_copy`` module option **destination_dataset** has been renamed to
    **dest_data_set**.

    * Review `version 1.4.0-beta.1` release notes for additional content.

Availability
------------

* `Galaxy`
* `GitHub`

Reference
---------

* Supported by `z/OS V2R3` or later
* Supported by the `z/OS® shell`
* Supported by `IBM Open Enterprise SDK for Python` v3.8.2 -
  `IBM Open Enterprise SDK for Python` v3.9.5
* Supported by IBM `Z Open Automation Utilities 1.1.0`_ and
  `Z Open Automation Utilities 1.1.1`

Known Issues
------------

* Review `version 1.4.0-beta.1` release notes for additional content.

Deprecation Notices
-------------------
* Review `version 1.4.0-beta.1` release notes for additional content.

2022-10-13 20:58 UTC, ddimatos commented
<img width="1069" alt="image" src="https://user-images.githubusercontent.com/25803172/195709094-7506d4fb-590c-4c56-b77f-17154dec6054.png">
URL suffix: `/job/zosAnsible/1284/consoleText`

2022-10-13 21:48 UTC, rexemin requested changes
Release notes look very good! I only noticed the typo above.

2022-10-13 21:48 UTC, rexemin commented on changelogs/changelog.yaml
> +        contents of it will be copied into the root of `dest`. It it doesn't end with
Typo here: it says "It it doesn't end..." when it should read "If it doesn't end..."

2022-10-13 22:21 UTC, rexemin approved these changes

2022-10-14 03:09 UTC, ddimatos commented
<img width="1046" alt="image" src="https://user-images.githubusercontent.com/25803172/195753379-6cd20252-8d92-488c-b3d6-27378f703a3f.png">
URL suffix: `/job/zosAnsible/1286/consoleText`

2022-10-14 03:47 UTC, merged