Bugfix/381/failed when the job name was null or not found
ansible-collections/ibm_zos_core pull request #747
Opened 2023-04-18 21:39 UTC by AndreMarcel99

##### SUMMARY
Add a variable to change the value depends of the parameters to jo_id, job_name or both.

Fixed #381 

##### ISSUE TYPE

- Bugfix Pull Request

##### COMPONENT NAME
Add variable name to change value depends on names.

##### ADDITIONAL INFORMATION
Change test where some values to support these Bugfix.
The logic is if the job_id and job_name are not given the message will be the _job_name with the job_id i_
In other case will verify will is given and just use as the job not founded.

<img width="899" alt="Captura de pantalla 2023-04-17 a la(s) 13 25 36" src="https://user-images.githubusercontent.com/68956970/232910354-1308e063-655c-4d1c-82f0-86329ec18387.png">
(Ignore the change in encode of utils, already in dev)

2023-04-19 00:15 UTC, ddimatos commented
Note that is a 1.7 work item, thus wait till we branch `dev` before trying to merge.

2023-04-24 14:35 UTC, fernandofloresg requested changes
Comments are in each file.

2023-04-24 14:35 UTC, fernandofloresg commented on plugins/module_utils/job.py
Correct me if I'm wrong but if job_id = 15 and job_name = '*', then return message would be "The job 15 could not be found.".
In a similar way, if job_id = '*' and job_name = "HELLOPGM", then return message would be "The job HELLOPGM could not be found."

I suggest two things:
1. Change the variable name to use a name that indicates the use of it i.e. job_not_found_msg, not_found_msg, ...
2. Change the job_not_founded message for those two cases above. Would rather have something like "The job with id 15 could not be found." and "The job with name HELLOPGM could not be found."

2023-04-24 16:21 UTC, AndreMarcel99 commented on plugins/module_utils/encode.py
It's in dev like that [here](https://github.com/ansible-collections/ibm_zos_core/blob/a856d18e9797f1d2eacf4ca7ab350b9f4cc3b390/plugins/module_utils/encode.py#L456) and [here](https://github.com/ansible-collections/ibm_zos_core/blob/a856d18e9797f1d2eacf4ca7ab350b9f4cc3b390/plugins/module_utils/encode.py#L499)

2023-04-24 16:32 UTC, AndreMarcel99 commented on plugins/module_utils/job.py
I will work with the second suggest, but about the first one, steps back in the code already take care of job_name='' or job_id='' put it a * as value [here](https://github.com/ansible-collections/ibm_zos_core/blob/336a7980e35951740e44055b6910252e33f4ef42/plugins/module_utils/job.py#L59)

2023-04-24 18:57 UTC, fernandofloresg requested changes
Overall looks good, just update those two details. zos_encode shouldn't appear in the PR at all.

2023-04-24 18:57 UTC, fernandofloresg commented on plugins/module_utils/encode.py
If there are not changes to this file could you just pull the branch dev version of it for this to stop appearing in the PR ? I'm afraid this would add the function a third time.

2023-04-24 18:57 UTC, fernandofloresg commented on changelogs/fragments/747-failed_when_the_job_name_was_null_or_not_found.yaml
> +- zos_job_output - Error message did not specify the job not found. Fix now specify the job_id or job_name searching for, to ensure more information to the user.
Please change the word "specify" to "specifies".

2023-04-24 22:23 UTC, fernandofloresg requested changes

2023-04-24 22:23 UTC, fernandofloresg commented on plugins/module_utils/encode.py
Caution! This will remove the file from dev... encode file shouldn't even appear in this PR if is identical to the one already in dev. Kindly checkout the latest from there.

2023-04-24 22:23 UTC, fernandofloresg commented on changelogs/fragments/747-failed_when_the_job_name_was_null_or_not_found.yaml
> +- zos_job_output - Error message did not specifies the job not found. Fix now specifies the job_id or job_name searching for, to ensure more information to the user.
I'm sorry I did not saw the first sentence. This should be worded like :
"Error message did not specify the job not found. Fix now specifies the job_id or job_name searching for, to ensure more information to the user."

2023-04-24 22:50 UTC, AndreMarcel99 commented on plugins/module_utils/encode.py
Is it solved?

2023-04-24 23:02 UTC, fernandofloresg commented on plugins/module_utils/encode.py
No, it still appears as before. Let me try something...

2023-04-24 23:22 UTC, fernandofloresg commented
@AndreMarcel99 That should be it. Had some issues going back and forth but overall issue was : 
1. Merge from dev
2. use git command `git checkout dev ./plugins/module_utils/encode.py` to checkout the file from the requested branch into the current branch
3. use git command `it diff bugfix/381/failed_when_the_job_name_was_null_or_not_found:plugins/module_utils/encode.py dev:plugins/module_utils/encode.py`

2023-04-24 23:30 UTC, fernandofloresg requested changes
Thank you so much for going through all the changes. Was a good exercise, only thing pending now is to run the pipeline and the comment about the change log.

2023-04-24 23:30 UTC, fernandofloresg commented on changelogs/fragments/747-failed_when_the_job_name_was_null_or_not_found.yaml
Sorry for still correcting this with new comments but just noticed. 

Correct tag is bugfixes not bugfix(even though is one). And GH is crying over the file not having a new line at the end kindly add it.

2023-04-25 23:00 UTC, rexemin commented on changelogs/fragments/747-failed_when_the_job_name_was_null_or_not_found.yaml
GitHub doesn't require the file to have a new line at the end. The symbol it's just there to indicate that it is there. Couldn't find in the style guidelines if fragments require newlines, so I think @AndreMarcel99 can leave the file as is.

2023-04-27 04:36 UTC, fernandofloresg commented on changelogs/fragments/747-failed_when_the_job_name_was_null_or_not_found.yaml
Thanks for clarification @rexemin

2023-04-28 16:29 UTC, AndreMarcel99 commented
<img width="1456" alt="Captura de pantalla 2023-04-25 a la(s) 12 02 27" src="https://user-images.githubusercontent.com/68956970/235203023-7273d628-f7b4-43c7-ab2d-d37f1a4ddfce.png">

With the branch update

2023-05-04 15:32 UTC, fernandofloresg approved these changes
Merged the latest from dev, was only doc changes no need to run the pipeline again. LGTM

2023-05-04 16:30 UTC, rexemin approved these changes
Looks good to me.

2023-05-04 23:59 UTC, ddimatos commented on changelogs/fragments/747-failed_when_the_job_name_was_null_or_not_found.yaml
I have noticed that too, we seem to build without it just fine, wish GH would not make it look so severe :(

2023-05-05 00:08 UTC, ddimatos commented on plugins/module_utils/job.py
BTW, i think (recalling from memory) , the reason fro the asterisk (`*`) is we can't query on None , we need to pass something to our query and we assume if there is no specifics we just go after everything. Speaking about this line of code `job_id = parsed_args.get("job_id") or "*"`

2023-05-05 00:20 UTC, ddimatos commented on plugins/module_utils/encode.py
Looks like this is resolved, i checkout the dev branch and searched this feature branch and could not find a duplicate `uss_tag_encoding`, might be helpful in the future for adhoc items like this add a PR or issue number to follow.

2023-05-05 03:55 UTC, ddimatos commented
See full regression `/job/zosAnsible/1721/console` 
<img width="1068" alt="image" src="https://user-images.githubusercontent.com/25803172/236374679-efe0d809-e79c-4b9b-a25c-ffb40e6eba36.png">

2023-05-05 03:55 UTC, merged