Bugfix/619/mode set for files applied test case
ansible-collections/ibm_zos_core pull request #757
Opened 2023-04-25 18:47 UTC by AndreMarcel99

##### SUMMARY
Add test case to ensure consistency and keep the bug fix #619 to not applied the change of mode to destination folder.

##### ISSUE TYPE
- Test case Pull Request

##### COMPONENT NAME
Test cases for zoo_copy one from file to folder and the other folder to folder.

##### ADDITIONAL INFORMATION
The test case create a dest folder and adjust to mode 750 that value of permissions is the one that will compare after the copy module is executed, after execute check permissions of dest folder to made the assertion.

Run pipeline
<img width="1456" alt="Captura de pantalla 2023-04-25 a la(s) 12 02 27" src="https://user-images.githubusercontent.com/68956970/234373277-7c2236bc-4390-4f0e-b9b4-20aa1caeb607.png">

2023-04-26 17:23 UTC, fernandofloresg commented
@AndreMarcel99 Please select at least 2 approvers, current rules need 2 approving reviews.

2023-04-26 17:48 UTC, fernandofloresg requested changes
Thanks for creating this test case, my comments are in line.

2023-04-26 17:48 UTC, fernandofloresg commented on tests/functional/modules/test_zos_copy_func.py
> +        hosts.all.shell(cmd="mkdir -p {0}".format(dest_path))
We should do things the same way as in other test cases, like creating folders, if you look at other test cases the preferred way to create a folder in the remote system is:

hosts.all.file(path=dest_path, state="directory")

2023-04-26 17:48 UTC, fernandofloresg commented on tests/functional/modules/test_zos_copy_func.py
> +        hosts.all.shell(cmd="mkdir -p {0}".format(dest_path))
Same as above test.

2023-04-26 17:51 UTC, fernandofloresg commented on tests/functional/modules/test_zos_copy_func.py
> +def test_copy_dest_directory_remain(ansible_zos_module, src):
Also, could you use a better descriptive name? test_copy_dest_directory_remain and test_copy_dest_folder_remain do not tell me about what both tests are testing

2023-04-26 17:54 UTC, fernandofloresg commented
This branch is 4 commits behind origin/dev with commits from 21 Apr, please make sure to merge from dev before executing the next pipeline build and test. This will ensure your test works well with latest dev changes.

As an advice, before branching out in your local to a `git pull` to ensure you are working on the latest version available.

2023-04-26 21:26 UTC, rexemin requested changes

2023-04-26 21:26 UTC, rexemin commented on tests/functional/modules/test_zos_copy_func.py
> +def test_ensure_copy_file_dont_change_permission_on_dest(ansible_zos_module, src):
This is a better test name, although it should read `test_ensure_copy_file_does_not_change_permission_on_dest`

2023-04-26 21:26 UTC, rexemin commented on tests/functional/modules/test_zos_copy_func.py
> +def test_ensure_copy_folder_dont_change_permission_on_dest(ansible_zos_module, src):
Same comment from above applies to this case: instead of using `dont` use `does_not`, and I'd use `directory` or `dir` instead of `folder`.

2023-04-26 21:26 UTC, rexemin commented on tests/functional/modules/test_zos_copy_func.py
>          hosts.all.shell(cmd="chmod 750 {0}".format(dest_path))
You can add `mode: "750"` to the `file` task above to set the permissions for the directory. Same for the other test.

2023-04-27 15:09 UTC, AndreMarcel99 commented
Thanks for all checks
<img width="1455" alt="Captura de pantalla 2023-04-27 a la(s) 9 07 41" src="https://user-images.githubusercontent.com/68956970/234905915-5f171fca-5701-4fa7-932b-0b9e80eaa4a4.png">

2023-04-27 18:59 UTC, fernandofloresg commented
@AndreMarcel99 Please run the pipeline in sync with dev branch 
![Screenshot 2023-04-27 at 12 57 37 PM](https://user-images.githubusercontent.com/23223623/234964542-29aaf39a-8fbf-4f3c-86e1-ee0d239e4140.png)

Once is ready for review, click on the symbol to request another review
![Screenshot 2023-04-27 at 12 58 23 PM](https://user-images.githubusercontent.com/23223623/234964741-a2869447-7250-48c6-86c8-46d31609aa60.png)

2023-04-28 19:24 UTC, AndreMarcel99 commented
Run of the pipeline with the branch update
<img width="1461" alt="Captura de pantalla 2023-04-28 a la(s) 13 23 32" src="https://user-images.githubusercontent.com/68956970/235235394-13d5bdef-def2-4801-b44d-d94382e72c61.png">

2023-05-04 15:33 UTC, fernandofloresg approved these changes
Merged the latest from dev, was only doc changes no need to run the pipeline again.

2023-05-04 23:50 UTC, ddimatos commented
@AndreMarcel99 - thank you for working with the team, although a small change had several comments, this is a good thing, the team is engaged, you are helping us out so much and great comments @fernandofloresg and @rexemin. I only came in to have a look and saw this was completed, so thank you from me. :).

2023-05-04 23:51 UTC, merged