v1.6.0 beta.1 release
ansible-collections/ibm_zos_core pull request #759
Opened 2023-04-26 21:28 UTC by ketankelkar

##### SUMMARY

Contains all changes for 1.6.0-beta.1 release including updated docs (.rst files), meta files, changelogs, release notes and of course updated module src code.

##### ISSUE TYPE
- New Beta Release PR

2023-04-26 22:28 UTC, ddimatos requested changes
Looks real good @ketankelkar nice job. I might suggest that @rexemin take a look at the zos_copy auto merge changes, overall everything I see here looks to be as it should

2023-04-26 22:28 UTC, ddimatos commented on docs/source/release_notes.rst
> +Version 1.6.0-beta.1
Missing space after "====" and then remove the other space after 1.6.0-beta.1

2023-04-26 22:28 UTC, ddimatos commented on docs/source/release_notes.rst
> +- ``zos_job_query`` - Enables embedded positional wild card placement throughout `job_name` and `job_id` parameters.
I don't think RST does anything with single single  back ticks "`" , if you double then `` you will get colorized text might be nice for the module properties, we did this in 1.4.0 doc as an example. Some other options here in the release notes might benefit.

2023-04-26 23:35 UTC, rexemin approved these changes
The changes to `zos_copy` look good to me.

2023-04-27 14:32 UTC, ddimatos commented
Full regression log `/job/zosAnsibleAlternate/54/consoleText`
<img width="1047" alt="image" src="https://user-images.githubusercontent.com/25803172/234895376-592d23c6-3a88-484e-86f1-6d13c4b27a4d.png">
Nice job, over 1000 test cases 👍

2023-04-27 17:25 UTC, ddimatos approved these changes
Looks good, thanks a bunch @ketankelkar

2023-04-27 17:26 UTC, merged