Bufix: Fixes zos_copy and zos_fetch deprecation msg for using _play_context.verbosity
ansible-collections/ibm_zos_core pull request #806
Opened 2023-06-14 07:22 UTC by ddimatos

##### SUMMARY
This addresses issue #779 where a deprecation warning would appear when zos_copy or zos_fetch ran. Of the two, the zos_copy module because its plugin is invoked immediately it could be automated, where as zos_fetch the plugin is second. 

In addition to this, the test case for #616 was addressed here because prevent proper pipeline execution

The pytest-ansible fixture was updated to support the zos_copy adhoc test case.

##### ISSUE TYPE

- Bugfix Pull Request
- Docs Pull Request
- Feature Pull Request
- New Module Pull Request

##### COMPONENT NAME

##### ADDITIONAL INFORMATION

```paste below

```

2023-06-15 05:43 UTC, ddimatos commented
@fernandofloresg - I requested you since you have similar work to do for the archive modules.
@AndreMarcel99 - I requested you because of the issue #616 , you had worked on it.

2023-06-15 05:44 UTC, ddimatos commented
Pipeline job `job/zosAnsibleAlternate2/51/console`
`======================= 541 passed in 8499.99s (2:21:39) =======================`
<img width="1057" alt="image" src="https://github.com/ansible-collections/ibm_zos_core/assets/25803172/54e85510-8be3-4df2-b82f-ee89d8b5baf2">

2023-06-15 17:14 UTC, fernandofloresg requested changes

2023-06-16 05:00 UTC, ddimatos commented on tests/functional/modules/test_zos_copy_func.py
> +       hosts.all.file(path=path, state="absent")
Its corrected now.

2023-06-16 12:17 UTC, AndreMarcel99 requested changes

2023-06-22 20:40 UTC, ddimatos commented on changelogs/fragments/791-zos_data_set-update-vsam-copy.yml
> +  UTF-8 failure. This change corrects and ensures the proper test coverage
Ill update it but:
corrects - fixes the bug
ensures - is saying it adds a test case. 

If no test case was added , corrects only would have been used.

2023-06-22 20:42 UTC, ddimatos commented on tests/functional/modules/test_zos_copy_func.py
> +            assert ("play context verbosity: "+ str(options["verbosity_level"])+"" in output)
It seems as if you want if `options["verbosity_level"]` set to a variable, that is fine but note that our pipe lines have other priorities now and this change should probably require a new pipeline run. Not sure we can spare the compute at this time to for a net zero change. 

Let me know.

2023-06-22 20:49 UTC, ddimatos commented
@fernandofloresg - changes made, I think you can resolve yours now. 
@AndreMarcel99 - one is resolved the other i had a comment to, let me know.

2023-06-22 21:06 UTC, AndreMarcel99 commented on tests/functional/modules/test_zos_copy_func.py
> +            assert ("play context verbosity: "+ str(options["verbosity_level"])+"" in output)
Ok. I'll going to add next iteration as a small change just to keep the consistency.

2023-06-23 00:32 UTC, fernandofloresg approved these changes

2023-06-27 17:31 UTC, AndreMarcel99 approved these changes

2023-06-27 17:31 UTC, merged