Bugfix for #807 - zos_copy ignores encoding for binary files
ansible-collections/ibm_zos_core pull request #810
Opened 2023-06-15 19:02 UTC by rexemin

##### SUMMARY
Fixes #807. Code introduced in 1.5.0 in `zos_copy` tried to convert the encoding of binary files, resulting in an error when the file was tagged as `binary` on z/OS or invalid bytes for UTF-8 were read.

##### ISSUE TYPE

- Bugfix Pull Request

##### COMPONENT NAME
zos_copy

##### ADDITIONAL INFORMATION
Added a couple of test cases to validate the handling of binary files.

2023-06-19 18:30 UTC, rexemin commented
![Screenshot 2023-06-19 at 11 28 48](https://github.com/ansible-collections/ibm_zos_core/assets/17365764/99d71edb-8291-4218-8a1c-2cfa132f88e4)
![Screenshot 2023-06-19 at 11 29 16](https://github.com/ansible-collections/ibm_zos_core/assets/17365764/df36337c-6cb9-486d-8002-66395a96704d)

2023-06-19 19:04 UTC, richp405 approved these changes
Nice, clean, straightforward.

2023-06-20 16:37 UTC, AndreMarcel99 requested changes

2023-06-20 16:37 UTC, AndreMarcel99 commented on tests/functional/modules/test_zos_copy_func.py
Personal view is to add a assertion to both cases to verify the content is fine.

2023-06-20 16:37 UTC, AndreMarcel99 commented on changelogs/fragments/810_fix_binary_file_bypass.yml
Is better: 
Fix makes sure that binary files bypass this normalization

2023-06-21 23:29 UTC, rexemin commented on tests/functional/modules/test_zos_copy_func.py
Agree that verifying the content should be in the tests, but because the destinations are binary datasets, the output that we can get from them is going to be finicky, and ZOAU 1.2.2 doesn't allow reading a dataset as a binary stream.

I decided to use the byte `FD` because it should trigger an error whenever the code tries to read it as text.

2023-06-21 23:30 UTC, rexemin commented on changelogs/fragments/810_fix_binary_file_bypass.yml
Updated the changelog accordingly.

2023-06-22 15:19 UTC, AndreMarcel99 commented on tests/functional/modules/test_zos_copy_func.py
Ok thanks for the answer, so for dev should be there the content.

2023-06-22 15:20 UTC, AndreMarcel99 commented
Thanks for the answer and the changes.

2023-06-22 21:40 UTC, ddimatos commented
Looks good thank you @rexemin

2023-06-22 21:40 UTC, merged