Bufix: Fixes zos_copy and zos_fetch deprecation msg for using _play_context.verbosity
ansible-collections/ibm_zos_core pull request #814
Opened 2023-06-16 05:25 UTC by ddimatos

Same as PR #806 but for release version 1.6.0.

##### SUMMARY
This addresses issue #779 where a deprecation warning would appear when zos_copy or zos_fetch ran. Of the two modules, only the `zos_copy` module  could be automated with a test because its plugin is invoked immediately where as with `zos_fetch` its invoked last and that can not work for testing display.verbosity.

In addition to this, the test case for #616 was addressed here because the original test case could not run properly on local work stations and the pipeline. So a new test case was written to run on both.

The pytest-ansible fixture was updated to support the `zos_copy` adhoc test case.

##### ISSUE TYPE

- Bugfix Pull Request

##### COMPONENT NAME

##### ADDITIONAL INFORMATION

```paste below

```

2023-06-20 03:02 UTC, rexemin commented
![Screenshot 2023-06-19 at 20 01 30](https://github.com/ansible-collections/ibm_zos_core/assets/17365764/500f27cc-f54e-45bc-855b-2869a9363892)
![Screenshot 2023-06-19 at 20 01 45](https://github.com/ansible-collections/ibm_zos_core/assets/17365764/5de7e453-339c-4b1f-b0bd-40b2d7334408)

2023-06-22 20:26 UTC, ddimatos commented
Thank you @rexemin your help getting this through was much appreciated.

2023-06-22 22:42 UTC, AndreMarcel99 approved these changes
Ready

2023-06-22 23:23 UTC, fernandofloresg requested changes

2023-06-22 23:23 UTC, fernandofloresg commented on changelogs/fragments/814-zos_data_set-update-vsam-copy.yml
> +bugfixes:changelogs/fragments/814-zos_data_set-update-vsam-copy.yml
This will break change log generation

2023-06-22 23:38 UTC, ddimatos commented on changelogs/fragments/814-zos_data_set-update-vsam-copy.yml
> +bugfixes:changelogs/fragments/814-zos_data_set-update-vsam-copy.yml
All fixed

2023-06-22 23:44 UTC, fernandofloresg approved these changes
🦭 of approval.

2023-06-22 23:48 UTC, merged