439 addf
ansible-collections/ibm_zos_core pull request #821
Opened 2023-06-19 21:04 UTC by richp405

##### SUMMARY
Add F parameter for data set creation, and in validation and inline docs.
Add test that uses F parameter and checks for errors.

Fixes 439

##### ISSUE TYPE
- Feature Pull Request

##### COMPONENT NAME
zos_data_set, data_set, and DataSet object

##### ADDITIONAL INFORMATION
Eliminates error message for record type='F', and passes value through to zoau.

```paste below

```

2023-06-19 21:27 UTC, richp405 commented
![image](https://github.com/ansible-collections/ibm_zos_core/assets/39140439/7d1711d3-7744-4b5c-a6a6-ab06fdd1deef)

Exclusions (things I didn't change, so the  builds would actually complete:
test_module_security.py,test_zos_blockinfile_func.py,
test_zos_find_func.py,/test_zos_mvs_raw_unit.py,test_zos_volume_init_func.py,test_zos_mvs_raw_func.py,
test_zos_backup_restore.py,test_zos_job_submit_func.py,test_zos_job_query_func.py,test_zos_mount_func.py,
test_zos_copy_func.py,modules/test_zos_fetch_func.py,test_zos_lineinfile_func.py,test_zos_job_output_func.py,
test_zos_encode_func.py,test_zos_apf_func.py

2023-06-21 16:29 UTC, fernandofloresg requested changes

2023-06-21 16:29 UTC, fernandofloresg commented on tests/functional/modules/test_zos_data_set_func.py
Looks good to me. This request might be out of scope, but could you instead parametrize this to test creating data sets with different formats? I would assume that test will be in place but didn't find it

2023-06-21 16:58 UTC, rexemin approved these changes
Looks good, thanks for adding it!

2023-06-21 19:38 UTC, richp405 commented on tests/functional/modules/test_zos_data_set_func.py
It was not in there.  I was hoping to just add 'F', but the other formats were not being tested.  Let me see if I can add them into a parameter loop.

2023-06-22 17:38 UTC, richp405 commented
Added a create test for each record_type in the test.

![image](https://github.com/ansible-collections/ibm_zos_core/assets/39140439/4bc8c4f1-92a4-4faa-b7e6-6c0e9eb521dd)

2023-06-22 21:41 UTC, fernandofloresg approved these changes
Great !

2023-06-23 17:19 UTC, merged