Enhancement/850/Redesining test cases to be clearer
ansible-collections/ibm_zos_core pull request #840
Opened 2023-07-10 14:53 UTC by AndreMarcel99

##### SUMMARY
The test cases for zos_blockinfile and zos_lineinfile was scattered and hard to follow, also include unnecessary test cases steps and sentences the new design is for be clear to read and solve some issues of datasets created.

##### ISSUE TYPE
- Bugfix Pull Request

##### COMPONENT NAME
Include a new design for test case base on the test as it is en every test not separate, also the expected output.

##### ADDITIONAL INFORMATION
The set environment and remove environment functions are separate because are the repeated structure in almost every test case. The rest is included in test cases and for special cases Is added tu full creation of environment and remove in the test itself just in case of follow steps and do not lose that important information. Lastly try to remove all dictionaries were all was summary and add every parameters definition in the test. 

For next enhanced will be added test cases for the encoding because it was not correctly tested and added a extra combination for all test cases in data sets.

<img width="1101" alt="Captura de pantalla 2023-07-10 a la(s) 8 52 45" src="https://github.com/ansible-collections/ibm_zos_core/assets/68956970/d16ad175-ebc1-41aa-9ee2-c89b82bd4463">

<img width="827" alt="Captura de pantalla 2023-07-10 a la(s) 8 53 20" src="https://github.com/ansible-collections/ibm_zos_core/assets/68956970/89c1155a-4dd7-4f7b-823f-2927846d9d11">

2023-07-12 21:44 UTC, AndreMarcel99 commented
<img width="1102" alt="Captura de pantalla 2023-07-12 a la(s) 15 42 20" src="https://github.com/ansible-collections/ibm_zos_core/assets/68956970/8376e94d-1e86-4818-8218-310214aa33cc">
<img width="630" alt="Captura de pantalla 2023-07-12 a la(s) 15 43 30" src="https://github.com/ansible-collections/ibm_zos_core/assets/68956970/ad210c44-07b2-416d-8487-2cb5534b8ca2">

Runs without any dictionaries

2023-07-13 21:44 UTC, richp405 approved these changes
The code change is significantly clearer, and the renaming of variables makes things better, as well.

2023-07-14 19:05 UTC, ddimatos requested changes
@AndreMarcel99 this is so much better than what we had before, I only made 2 comments but they apply to all test cases which are:
1) You can simplify the code if you want a bit by inspecting the stack to get the function name, its a bit expensive but probably worth it if we are reducing code and make it more flexible, eg `est_folder = "/tmp/ansible-core-tests/zos_blockinfile" + inspect.stack()[0][3]`
2) Move all the expected results into a variable at the top of the function is what the team decided was easier to read
3) Add 2 encoding tests , one for USS files and one for Data sets, i don't think we need more than 2 positive test cases, probably best to use the encoding module to help and then do the same for lineinfile.

2023-07-14 21:58 UTC, rexemin reviewed
Changes look really good, thank you for cleaning these tests up! I agree with Demetri's comments and don't really have anything else to add, so I'll approve when you make the changes.

2023-07-17 15:17 UTC, AndreMarcel99 commented on tests/functional/modules/test_zos_blockinfile_func.py
> +            assert result.get("stdout") == """if [ -z STEPLIB ] && tty -s;
The test for encoding of datasets, required specify texts

2023-07-17 15:18 UTC, AndreMarcel99 commented
<img width="1096" alt="Captura de pantalla 2023-07-17 a la(s) 9 16 39" src="https://github.com/ansible-collections/ibm_zos_core/assets/68956970/4cd0ede1-a50b-41eb-a5a0-425571c64309">
New Run

2023-07-17 22:35 UTC, ddimatos commented on tests/functional/modules/test_zos_blockinfile_func.py
> +            assert result.get("stdout") == """if [ -z STEPLIB ] && tty -s;
Thanks for resolving the expected values into a variable.

2023-07-18 00:54 UTC, AndreMarcel99 commented
<img width="1099" alt="Captura de pantalla 2023-07-17 a la(s) 18 53 48" src="https://github.com/ansible-collections/ibm_zos_core/assets/68956970/8f7c946f-c2d0-477d-baf2-94b29c55a9ce">

2023-07-18 20:05 UTC, ddimatos approved these changes
Looks good to me, thanks for all the hard work and the updates, this is an amazing cleanup.

2023-07-18 20:06 UTC, merged