Initial commit to add LIBRARY to choices and docs
ansible-collections/ibm_zos_core pull request #968
Opened 2023-09-14 19:01 UTC by richp405

##### SUMMARY
Change to zos_copy:
Added LIBRARY type to dest_dataset/suboptions as a valid choice
Updated in file documentation to reflect the option

Fixes 920

##### ISSUE TYPE
- Bugfix Pull Request (missing option)
- Docs Pull Request (added option)

##### COMPONENT NAME
zos_copy.py

2023-09-16 00:12 UTC, ketankelkar reviewed
LGTM - curious to know what kind of validation can be done (both docs-wise and functionally). I don't anticipate any hiccups

2023-10-03 17:24 UTC, fernandofloresg requested changes
Seems really straightforward, can we add a test for it ?

2023-10-03 17:24 UTC, fernandofloresg commented on changelogs/fragments/920-bug-add-library-feature-documentation.yml
There are two changelog fragments for this PR, please keep only one

2023-10-04 14:12 UTC, richp405 commented on changelogs/fragments/920-bug-add-library-feature-documentation.yml
oops!  I've removed the bug version

2023-10-04 15:16 UTC, richp405 commented
> Seems really straightforward, can we add a test for it ?

@fernandofloresg I'm not sure.. there don't appear to be tests to the other destination subtypes, so I'm not sure if we should add another test here.

2023-10-06 05:38 UTC, ddimatos commented
> > Seems really straightforward, can we add a test for it ?
> 
> @fernandofloresg I'm not sure.. there don't appear to be tests to the other destination subtypes, so I'm not sure if we should add another test here.

@fernandofloresg @richp405 , LIBRARY ultimately maps to PDSE in the lower layers of the code, testing LIBRARY is tested by zos_data_set since its the shared module_utility used to create these data sets, the only thing that might need validation is that our module correctly pass along the option till the shared code. 

To actually test a library,[ the easiest but fairly costly test case would be to replicate the load module test](https://github.com/ansible-collections/ibm_zos_core/blob/516df020117ad0854f788f416b7c9bd225c7d876/tests/functional/modules/test_zos_copy_func.py#L2537) and instead of using a PDSE to write the load module into, write it into a type LIBRARY. We could also have @ketankelkar see if he could add a LIBRARY test when they write the alias tests as there will be new load module tests. 

Low level code I mentioned:
```
if (!argstrnocasecmp(remainder, TYPE_PDSE) || !argstrnocasecmp(remainder, TYPE_LIBRARY)) {
		setDynParm(dynParms, Dsntype, __DSNT_LIBRARY);
		if (!dynParms[Dsorg].used) {
			setDynParm(dynParms, Dsorg, __DSORG_PO);
		}
```

2023-10-06 05:48 UTC, ddimatos commented
I generated and pushed up the updated doc to reflect this change directly into the branch, you can see the *.rst and screen capture below:
<img width="663" alt="image" src="https://github.com/ansible-collections/ibm_zos_core/assets/25803172/8d9efc6c-4e9a-440e-b4c8-1a459cc27320">

2023-10-06 05:51 UTC, ddimatos commented
> LGTM - curious to know what kind of validation can be done (both docs-wise and functionally). I don't anticipate any hiccups

@ketankelkar , i generated doc for this PR , saw that was missing, short of a manual playbook test the only other type of check/test we can do is to write a test case using LIBRARY which is call the module_utils and tested there but maybe we can tweak a load module test to use a LIBRARY data set instead of a PDSE (they are the same).

2023-10-06 05:53 UTC, ketankelkar commented
I found this test case near the very bottom: [test_dest_data_set_parameters](https://github.com/ansible-collections/ibm_zos_core/blob/516df020117ad0854f788f416b7c9bd225c7d876/tests/functional/modules/test_zos_copy_func.py#L3401), maybe it can be augmented with other data set types too, it looks like it's currently only testing sequential data sets.

I'd be happy to add it into the loadlib test cases too! I'll pull in your changes

2023-10-06 05:58 UTC, ddimatos approved these changes
@richp405 This looks good to me, I commented on a few of the discussions about testing this, I think this can be tested by the alias function which is creating a number of new executable tests which are already expensive in time, don't think we need a test simply just for Library when we can test library with alias support. Thank you.

2023-10-06 14:59 UTC, richp405 commented
@fernandofloresg Based on the conversation above (DD and Ketan)... are you okay with that as a test for this?

2023-10-06 22:08 UTC, ketankelkar commented
I updated my branch (`enhancement/423/zos_copy-add-data-set-member-alias-support`) with the latest `dev` and then only modified the two lines this PR changed up in zos_copy.py 
here's the git diff:
![image](https://github.com/ansible-collections/ibm_zos_core/assets/10567394/53430382-9d71-4c4c-9914-c3c9afb76ead)

I modified the test cases with loadlibs and switched the `type: pdse` to `type: library`. 
e.g.:
![image](https://github.com/ansible-collections/ibm_zos_core/assets/10567394/40bd555a-de6f-4838-9c16-7d2335f15222)
![image](https://github.com/ansible-collections/ibm_zos_core/assets/10567394/eed30a9e-3cab-4f23-8ffa-45cfad0f8f0d)

And all the test cases with loadlibs passed
![image](https://github.com/ansible-collections/ibm_zos_core/assets/10567394/a82b9fba-9b37-4b7d-8581-6162e573d7a3)

Note- i created a new pytest "mark" called loadlibs and marked all the test cases I found with loadlibs.

2023-10-06 23:22 UTC, ketankelkar commented
my comment above was a bit misguided, i modified the `test_copy_pds_loadlib_to_pds_loadlib` test case to run with and without pre-allocated destination data sets. In the variation without pre-allocated data sets, I invoke `zos_copy` with the `dest_data_set` option and pass in 'LIBRARY' as a value.

```python
        if not is_created:
            # dest data set does not exist, specify it in dest_dataset param.
            # copy src loadlib to dest library pds w/o aliases
            copy_res = hosts.all.zos_copy(
                src="{0}".format(src_lib),
                dest="{0}".format(dest_lib),
                remote_src=True,
                executable=True,
                aliases=False,
                dest_data_set={
                    'type': "LIBRARY",
                    'record_format': "U",
                    'record_length': 0,
                    'block_size': 32760,
                    'space_primary': 2,
                    'space_type': "M",
                }
            )
            # copy src loadlib to dest library pds w aliases
            copy_res_aliases = hosts.all.zos_copy(
                src="{0}".format(src_lib),
                dest="{0}".format(dest_lib_aliases),
                remote_src=True,
                executable=True,
                aliases=True,
                dest_data_set={
                    'type': "LIBRARY",
                    'record_format': "U",
                    'record_length': 0,
                    'block_size': 32760,
                    'space_primary': 2,
                    'space_type': "M",
                }
            )
```

As the image shows, both variations of this test case pass:
![image](https://github.com/ansible-collections/ibm_zos_core/assets/10567394/979c1c68-a9b3-44cb-ae75-e34a022420b4)

2023-10-07 05:19 UTC, ddimatos commented
@ketankelkar thanks so much, looks like you cover the LIBRARY test in your alias branch work which just came up for review today.

2023-10-08 00:13 UTC, fernandofloresg approved these changes
is ok for me @richp405

2023-10-10 18:42 UTC, merged